import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { db } from "./db.js";
import { errors } from "./errors.js";
import { requireHousehold } from "./authorize.js";

const params=z.object({householdId:z.string().uuid()});
const itemParams=params.extend({itemId:z.string().uuid()});
const body=z.object({name:z.string().trim().min(1).max(120),onHand:z.boolean().default(true)});
const patch=body.extend({version:z.number().int().positive()});
const common=["Salt","Black Pepper","Garlic Powder","Onion Powder","Paprika","Smoked Paprika","Cinnamon","Basil","Oregano","Parsley","Rosemary","Sage","Thyme","Bay Leaves","Dill","Cumin","Chili Powder","Cayenne Pepper","Crushed Red Pepper","Turmeric","Coriander","Mustard Powder","Italian Seasoning","Taco Seasoning","Cajun Seasoning","Poultry Seasoning","Everything Bagel Seasoning"];
const normalize=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
export async function spiceCabinetRoutes(app:FastifyInstance){
 app.get("/api/v1/households/:householdId/spice-cabinet",async request=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId);return db.spiceCabinetItem.findMany({where:{householdId},orderBy:[{onHand:"desc"},{name:"asc"}]});});
 app.post("/api/v1/households/:householdId/spice-cabinet",async(request,reply)=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId,true);const input=body.parse(request.body);const normalizedName=normalize(input.name);const row=await db.$transaction(async tx=>{const item=await tx.spiceCabinetItem.upsert({where:{householdId_normalizedName:{householdId,normalizedName}},create:{householdId,name:input.name,normalizedName,onHand:input.onHand,createdByUserId:request.authUser!.id,updatedByUserId:request.authUser!.id},update:{name:input.name,onHand:input.onHand,version:{increment:1},updatedByUserId:request.authUser!.id}});await tx.auditEvent.create({data:{actorUserId:request.authUser!.id,householdId,action:"spice-cabinet.item.saved",resourceType:"SpiceCabinetItem",resourceId:item.id,result:"success",correlationId:request.correlationId,metadata:{name:item.name,onHand:item.onHand}}});return item;});return reply.code(201).send(row);});
 app.patch("/api/v1/households/:householdId/spice-cabinet/:itemId",async request=>{const {householdId,itemId}=itemParams.parse(request.params);await requireHousehold(request,householdId,true);const input=patch.parse(request.body),normalizedName=normalize(input.name);const result=await db.spiceCabinetItem.updateMany({where:{id:itemId,householdId,version:input.version},data:{name:input.name,normalizedName,onHand:input.onHand,version:{increment:1},updatedByUserId:request.authUser!.id}});if(result.count!==1)throw errors.conflict();return db.spiceCabinetItem.findUniqueOrThrow({where:{id:itemId}});});
 app.delete("/api/v1/households/:householdId/spice-cabinet/:itemId",async(request,reply)=>{const {householdId,itemId}=itemParams.parse(request.params);await requireHousehold(request,householdId,true);const version=Number((request.query as {version?:string}).version);if(!Number.isInteger(version))throw errors.conflict();const result=await db.spiceCabinetItem.deleteMany({where:{id:itemId,householdId,version}});if(result.count!==1)throw errors.conflict();return reply.code(204).send();});
 app.post("/api/v1/households/:householdId/spice-cabinet/seed",async request=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId,true);await db.$transaction(common.map(name=>db.spiceCabinetItem.upsert({where:{householdId_normalizedName:{householdId,normalizedName:normalize(name)}},create:{householdId,name,normalizedName:normalize(name),onHand:false,createdByUserId:request.authUser!.id,updatedByUserId:request.authUser!.id},update:{}})));return db.spiceCabinetItem.findMany({where:{householdId},orderBy:{name:"asc"}});});
}
