import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { db } from "./db.js";
import { errors } from "./errors.js";
import { requireHousehold } from "./authorize.js";
import { canonicalSpiceName } from "./spice-recognition.js";

const params=z.object({householdId:z.string().uuid()});
const itemParams=params.extend({itemId:z.string().uuid()});
const body=z.object({name:z.string().trim().min(1).max(120),onHand:z.boolean().default(true)});
const patch=body.extend({version:z.number().int().positive()});
const common=["Salt","Black Pepper","Garlic Powder","Onion Powder","Paprika","Smoked Paprika","Cinnamon","Basil","Oregano","Parsley","Rosemary","Sage","Thyme","Bay Leaves","Dill","Cumin","Chili Powder","Cayenne Pepper","Crushed Red Pepper","Turmeric","Coriander","Mustard Powder","Italian Seasoning","Taco Seasoning","Cajun Seasoning","Poultry Seasoning","Everything Bagel Seasoning","White Pepper","Nutmeg","Ginger","Allspice","Cloves","Cardamom","Curry Powder","Garam Masala"];
export const normalizeSpiceName=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const normalize=normalizeSpiceName;
const commonNormalized=new Set(common.map(normalize));
export function commonSpiceSummary(names:string[]){const present=new Set(names.map(normalize).filter(name=>commonNormalized.has(name)));return{total:common.length,present:present.size,missing:common.length-present.size,complete:present.size===common.length};}
export async function spiceCabinetRoutes(app:FastifyInstance){
 app.get("/api/v1/households/:householdId/spice-cabinet",async request=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId);return db.spiceCabinetItem.findMany({where:{householdId},orderBy:[{onHand:"desc"},{name:"asc"}]});});
 app.post("/api/v1/households/:householdId/spice-cabinet",async(request,reply)=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId,true);const input=body.parse(request.body);const normalizedName=normalize(input.name);const row=await db.$transaction(async tx=>{const item=await tx.spiceCabinetItem.upsert({where:{householdId_normalizedName:{householdId,normalizedName}},create:{householdId,name:input.name,normalizedName,onHand:input.onHand,createdByUserId:request.authUser!.id,updatedByUserId:request.authUser!.id},update:{name:input.name,onHand:input.onHand,version:{increment:1},updatedByUserId:request.authUser!.id}});await tx.auditEvent.create({data:{actorUserId:request.authUser!.id,householdId,action:"spice-cabinet.item.saved",resourceType:"SpiceCabinetItem",resourceId:item.id,result:"success",correlationId:request.correlationId,metadata:{name:item.name,onHand:item.onHand}}});return item;});return reply.code(201).send(row);});
 app.patch("/api/v1/households/:householdId/spice-cabinet/:itemId",async request=>{const {householdId,itemId}=itemParams.parse(request.params);await requireHousehold(request,householdId,true);const input=patch.parse(request.body),normalizedName=normalize(input.name);return db.$transaction(async tx=>{const current=await tx.spiceCabinetItem.findFirst({where:{id:itemId,householdId,version:input.version}});if(!current)throw errors.conflict();const item=await tx.spiceCabinetItem.update({where:{id:itemId},data:{name:input.name,normalizedName,onHand:input.onHand,version:{increment:1},updatedByUserId:request.authUser!.id}});if(input.onHand){const list=await tx.groceryList.findFirst({where:{householdId,status:"ACTIVE"},orderBy:{updatedAt:"desc"}});if(list){const names=new Set([current.normalizedName,normalizedName,normalize(canonicalSpiceName(current.name)??current.name),normalize(canonicalSpiceName(input.name)??input.name)]);await tx.groceryListItem.deleteMany({where:{groceryListId:list.id,checked:false,normalizedName:{in:[...names]}}});}}return item;});});
 app.delete("/api/v1/households/:householdId/spice-cabinet/:itemId",async(request,reply)=>{const {householdId,itemId}=itemParams.parse(request.params);await requireHousehold(request,householdId,true);const version=Number((request.query as {version?:string}).version);if(!Number.isInteger(version))throw errors.conflict();const result=await db.spiceCabinetItem.deleteMany({where:{id:itemId,householdId,version}});if(result.count!==1)throw errors.conflict();return reply.code(204).send();});
 app.post("/api/v1/households/:householdId/spice-cabinet/seed",async request=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId,true);await db.$transaction(common.map(name=>db.spiceCabinetItem.upsert({where:{householdId_normalizedName:{householdId,normalizedName:normalize(name)}},create:{householdId,name,normalizedName:normalize(name),onHand:false,createdByUserId:request.authUser!.id,updatedByUserId:request.authUser!.id},update:{}})));return db.spiceCabinetItem.findMany({where:{householdId},orderBy:{name:"asc"}});});
 app.get("/api/v1/households/:householdId/spice-cabinet/status",async request=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId);const [items,list]=await Promise.all([db.spiceCabinetItem.findMany({where:{householdId},orderBy:{name:"asc"}}),db.groceryList.findFirst({where:{householdId,status:"ACTIVE"},include:{items:{where:{checked:false}}},orderBy:{updatedAt:"desc"}})]);const shopping=new Set((list?.items??[]).map(item=>item.normalizedName));return{items:items.map(item=>({...item,inShopping:shopping.has(item.normalizedName),isCommon:commonNormalized.has(item.normalizedName)})),common:commonSpiceSummary(items.map(item=>item.name)),initialized:items.length>0};});
app.post("/api/v1/households/:householdId/spice-cabinet/missing-to-shopping",async request=>{const {householdId}=params.parse(request.params);await requireHousehold(request,householdId,true);const body=z.object({itemIds:z.array(z.string().uuid()).optional()}).strict().parse(request.body??{});return db.$transaction(async tx=>{const spices=await tx.spiceCabinetItem.findMany({where:{householdId,onHand:false,...(body.itemIds?{id:{in:body.itemIds}}:{})}});let list=await tx.groceryList.findFirst({where:{householdId,status:"ACTIVE"},include:{items:true},orderBy:{updatedAt:"desc"}});if(!list)list=await tx.groceryList.create({data:{householdId,name:"Current List",status:"ACTIVE",createdByUserId:request.authUser!.id},include:{items:true}});const existing=new Set(list.items.filter(x=>!x.checked).map(x=>x.normalizedName));let created=0,alreadyPresent=0;for(const spice of spices){const canonical=canonicalSpiceName(spice.name)??spice.name;const normalized=normalize(canonical);if(existing.has(normalized)){alreadyPresent++;continue;}await tx.groceryListItem.create({data:{groceryListId:list.id,name:canonical,normalizedName:normalized,checked:false}});existing.add(normalized);created++;}return{created,alreadyPresent,listId:list.id};});});

}
