import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { db } from "./db.js";
import { errors } from "./errors.js";
function requireSupport(request: FastifyRequest) {
  if (!request.authUser) throw errors.unauthorized();
  if (request.authUser.applicationRole !== "SUPPORT" && request.authUser.applicationRole !== "SUPER_ADMIN") throw errors.forbidden();
}
const paging=z.object({q:z.string().trim().max(120).optional(),take:z.coerce.number().int().min(1).max(100).default(50)});
export async function supportRoutes(app: FastifyInstance) {
  app.get("/api/v1/support/me", async request => { requireSupport(request); return { user:{id:request.authUser!.id,email:request.authUser!.primaryEmail,displayName:request.authUser!.displayName,role:request.authUser!.applicationRole} }; });
  app.get("/api/v1/support/overview", async request => { requireSupport(request); const now=new Date(), d7=new Date(now.getTime()-7*86400000); const [users,households,activeSessions,recentUsers,recentEvents]=await Promise.all([db.user.count(),db.household.count(),db.userSession.count({where:{revokedAt:null,expiresAt:{gt:now},absoluteExpiresAt:{gt:now}}}),db.user.count({where:{lastLoginAt:{gte:d7}}}),db.auditEvent.findMany({orderBy:{occurredAt:"desc"},take:12,select:{id:true,action:true,resourceType:true,result:true,correlationId:true,occurredAt:true,actorUserId:true,householdId:true}})]); return {checkedAt:now,metrics:{users,households,activeSessions,activeUsers7d:recentUsers,openIssues:0},recentEvents}; });
  app.get("/api/v1/support/users", async request => { requireSupport(request); const {q,take}=paging.parse(request.query); const users=await db.user.findMany({...(q?{where:{OR:[{primaryEmail:{contains:q,mode:"insensitive"}},{displayName:{contains:q,mode:"insensitive"}}]}}:{}),orderBy:{lastLoginAt:"desc"},take,select:{id:true,displayName:true,primaryEmail:true,status:true,applicationRole:true,createdAt:true,lastLoginAt:true,_count:{select:{sessions:true,memberships:true}}}}); return {items:users}; });
  app.get("/api/v1/support/sessions", async request => { requireSupport(request); const {take}=paging.parse(request.query); const now=new Date(); const items=await db.userSession.findMany({orderBy:{lastSeenAt:"desc"},take,select:{id:true,createdAt:true,lastSeenAt:true,expiresAt:true,absoluteExpiresAt:true,revokedAt:true,user:{select:{id:true,displayName:true,primaryEmail:true}}}}); return {items:items.map(x=>({...x,status:x.revokedAt?"REVOKED":x.expiresAt<=now||x.absoluteExpiresAt<=now?"EXPIRED":"ACTIVE"}))}; });
  app.post("/api/v1/support/sessions/:sessionId/revoke", async request => { requireSupport(request); const {sessionId}=z.object({sessionId:z.string().uuid()}).parse(request.params); const target=await db.userSession.update({where:{id:sessionId},data:{revokedAt:new Date()}}); await db.auditEvent.create({data:{actorUserId:request.authUser!.id,action:"support.session.revoke",resourceType:"UserSession",resourceId:sessionId,result:"SUCCESS",correlationId:request.correlationId,metadata:{targetUserId:target.userId}}}); return {revoked:true}; });
  app.get("/api/v1/support/activity", async request => { requireSupport(request); const {q,take}=paging.parse(request.query); const items=await db.auditEvent.findMany({...(q?{where:{OR:[{correlationId:{contains:q,mode:"insensitive"}},{action:{contains:q,mode:"insensitive"}}]}}:{}),orderBy:{occurredAt:"desc"},take,select:{id:true,action:true,resourceType:true,resourceId:true,result:true,correlationId:true,occurredAt:true,actorUserId:true,householdId:true,metadata:true}}); return {items}; });
}
